### PR TITLE
Edit to vis.vis_cpu to re-introduce freq factor that somehow got dele…

### PR DESCRIPTION
**Pull request by AaronParsons**
…ted several months ago and committed.

### CODE REVIEW

**Comment by steven-murray** [comment]
This fails because of an error in hera_cal, which really just doesn't have to be installed anyway. If you remove the hera_cal line from the .travis.yml, then it should test OK, and we can merge.

**Comment by jsdillon** [comment]
Why is hera_cal erroring? We're passing our own tests.

**Comment by steven-murray** [comment]
@jsdillon it is failing when attempting to install hera_cal, complaining that sklearn is not installed. We could just install it before hera_cal, of course, but AFAICT hera_sim does not need hera_cal anyway (except for in the notebook tutorial), so we could probably just not have it in the .travis.yml install process.

**Comment by steven-murray** [comment]
We've decided that even though hera_cal is not currently used, it will be soon, so we should just add scikit-learn to the .travis.yml installation process.

**Comment by steven-murray** [comment]
I will make this fix in the Simulator branch, so don't worry about it here. Let's just pull this in.

**Pull request merged**
