### PR TITLE
fix: don't simulate xtalk for autos

### PR DESCRIPTION
**Pull request by r-pascua**
I forgot to make sure that the new cross-coupling model is only applied to cross-correlations. This has been fixed.

### CODE REVIEW

**Comment by aewallwi** [comment]
> I forgot to make sure that the new cross-coupling model is only applied to cross-correlations. This has been fixed.

Why do we have to apply this only to cross correlations? I think that the autos might be a good place to check for cross coupling effects as well.

**Comment by r-pascua** [comment]
@aewallwi this model is only valid for the cross-correlations. The autos would need a different model. In particular, the cross-coupling visibility would be the sum of all of the cross-correlations, with each cross-correlation scaled by an appropriate choice of reflection coefficient. The model here would effectively rescale the input auto to (1 + eps) times itself, with eps being the reflection coefficient for the particular antenna. In the previous validation effort, we also excluded cross-coupling from the autos, since it's effectively a second-order effect.

**Comment by aewallwi** [comment]
Ah! Thanks for clarifying! I thought this was for the Josaitis cross-talk model. This is definitely fine with me!

**Review by steven-murray — APPROVED** [review]
Perfect, thanks @r-pascua

**Comment by steven-murray** [comment]
Oh add to the changelog :-)

**Comment by r-pascua** [comment]
Thanks for the reminder! I will log the changes.

**Review by steven-murray — APPROVED** [review]

**Pull request merged**
