### PR TITLE
Visibility Simulator 2.0.0 tutorial

### PR DESCRIPTION
**Pull request by piyanatk**
This PR updates the visibility simulator tutorial to the new `hera_sim>=2.0.0` interface. It also remove old unused tutorial data and add a new sub-directory structure in the `DATA_PATH`, so that tutorial data can be easily retrieved and followed along. `MANIFEST.in` is also added to recursively search this subdirectory structure and include the files in `package_data`.

### CODE REVIEW

**Comment by piyanatk** [comment]
<p>Thanks! Added the motivation.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera_sim/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by piyanatk** [comment]
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera_sim/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by piyanatk** [comment]
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera_sim/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by piyanatk** [comment]
<p>Add "Creating a Custom Simulator"</p><p> </p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera_sim/pull/189/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by piyanatk** [comment]
Thanks @steven-murray and @r-pascua for feedback. I have updated the tutorials. Here are the changes (also in the commit log.)

Changes:
* Moved description of the underlying ModelData object to before Example 1.
* Moved "Accesing Simulation Parameters and Visibility" to right after Example 1.
* Adjusted some plots per suggestions
* Fixed typos per suggesions
* "Constructing a SkyModel" section:
    * Change HEALPix diffuse model to unifomrly random distribution
    * Adjusted source flux density values
    * Added a few cells to run simulations with the created sky models
     and compare visibilities.
* "Simulator Choices" section:
    * Explicitly said that use_beam_pixel is default for VisCPU
    * Added "Creating a Custom Simulator"

**Review by steven-murray — APPROVED** [review]
This looks good to me, thanks @piyanatk for this amazing work!

**Pull request merged**
